import type { Migration } from './types';

export const phase5Migrations: Migration[] = [
  {
    id: '0004_phase5_script_versions',
    version: 4,
    statements: [
      `CREATE TABLE IF NOT EXISTS agent_runs (
        id TEXT PRIMARY KEY,
        project_id TEXT NOT NULL,
        episode_id TEXT,
        skill_version_id TEXT,
        model_config_id TEXT,
        action TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'queued',
        input_json TEXT NOT NULL DEFAULT '{}',
        output_artifact_id TEXT,
        usage_json TEXT NOT NULL DEFAULT '{}',
        error_message TEXT NOT NULL DEFAULT '',
        started_at INTEGER,
        completed_at INTEGER,
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL,
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
        FOREIGN KEY (episode_id) REFERENCES episodes(id) ON DELETE SET NULL,
        FOREIGN KEY (skill_version_id) REFERENCES skill_versions(id) ON DELETE SET NULL,
        FOREIGN KEY (model_config_id) REFERENCES model_configs(id) ON DELETE SET NULL,
        FOREIGN KEY (output_artifact_id) REFERENCES artifacts(id) ON DELETE SET NULL
      )`,
      'CREATE INDEX IF NOT EXISTS agent_runs_project_idx ON agent_runs (project_id, action, status)',
      `CREATE TABLE IF NOT EXISTS story_outlines (
        id TEXT PRIMARY KEY,
        project_id TEXT NOT NULL,
        source_document_id TEXT,
        agent_run_id TEXT,
        title TEXT NOT NULL DEFAULT '',
        content TEXT NOT NULL,
        artifact_id TEXT,
        status TEXT NOT NULL DEFAULT 'draft',
        revision INTEGER NOT NULL DEFAULT 1,
        version_no INTEGER NOT NULL DEFAULT 1,
        quality_gate_id TEXT,
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL,
        deleted_at INTEGER,
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
        FOREIGN KEY (source_document_id) REFERENCES source_documents(id) ON DELETE SET NULL,
        FOREIGN KEY (agent_run_id) REFERENCES agent_runs(id) ON DELETE SET NULL,
        FOREIGN KEY (artifact_id) REFERENCES artifacts(id) ON DELETE SET NULL
      )`,
      'CREATE INDEX IF NOT EXISTS story_outlines_project_idx ON story_outlines (project_id, deleted_at, version_no)',
      `CREATE TABLE IF NOT EXISTS adaptation_plans (
        id TEXT PRIMARY KEY,
        project_id TEXT NOT NULL,
        story_outline_id TEXT,
        agent_run_id TEXT,
        scope TEXT NOT NULL DEFAULT 'global',
        episode_id TEXT,
        episode_index INTEGER,
        content TEXT NOT NULL,
        artifact_id TEXT,
        status TEXT NOT NULL DEFAULT 'draft',
        revision INTEGER NOT NULL DEFAULT 1,
        version_no INTEGER NOT NULL DEFAULT 1,
        quality_gate_id TEXT,
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL,
        deleted_at INTEGER,
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
        FOREIGN KEY (story_outline_id) REFERENCES story_outlines(id) ON DELETE SET NULL,
        FOREIGN KEY (agent_run_id) REFERENCES agent_runs(id) ON DELETE SET NULL,
        FOREIGN KEY (episode_id) REFERENCES episodes(id) ON DELETE SET NULL,
        FOREIGN KEY (artifact_id) REFERENCES artifacts(id) ON DELETE SET NULL
      )`,
      'CREATE INDEX IF NOT EXISTS adaptation_plans_project_idx ON adaptation_plans (project_id, scope, episode_index, deleted_at)',
      `CREATE TABLE IF NOT EXISTS script_versions (
        id TEXT PRIMARY KEY,
        project_id TEXT NOT NULL,
        episode_id TEXT NOT NULL,
        episode_index INTEGER NOT NULL,
        title TEXT NOT NULL DEFAULT '',
        content TEXT NOT NULL,
        artifact_id TEXT,
        source TEXT NOT NULL DEFAULT 'manual_edit',
        status TEXT NOT NULL DEFAULT 'draft',
        revision INTEGER NOT NULL DEFAULT 1,
        version_no INTEGER NOT NULL DEFAULT 1,
        quality_status TEXT NOT NULL DEFAULT 'unchecked',
        agent_run_id TEXT,
        metadata_json TEXT NOT NULL DEFAULT '{}',
        locked_at INTEGER,
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL,
        deleted_at INTEGER,
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
        FOREIGN KEY (episode_id) REFERENCES episodes(id) ON DELETE CASCADE,
        FOREIGN KEY (artifact_id) REFERENCES artifacts(id) ON DELETE SET NULL,
        FOREIGN KEY (agent_run_id) REFERENCES agent_runs(id) ON DELETE SET NULL
      )`,
      'CREATE INDEX IF NOT EXISTS script_versions_project_episode_idx ON script_versions (project_id, episode_index, deleted_at, version_no)',
      `CREATE TABLE IF NOT EXISTS quality_gates (
        id TEXT PRIMARY KEY,
        project_id TEXT NOT NULL,
        object_type TEXT NOT NULL,
        object_id TEXT NOT NULL,
        metric TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'unchecked',
        scope_json TEXT NOT NULL DEFAULT '{}',
        denominator INTEGER NOT NULL DEFAULT 0,
        passed_count INTEGER NOT NULL DEFAULT 0,
        failed_items_json TEXT NOT NULL DEFAULT '[]',
        confidence REAL NOT NULL DEFAULT 0,
        sampling_rule TEXT NOT NULL DEFAULT '',
        review_source TEXT NOT NULL DEFAULT 'manual_review',
        operator_decision TEXT NOT NULL DEFAULT '',
        waiver_reason TEXT NOT NULL DEFAULT '',
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL,
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
      )`,
      'CREATE INDEX IF NOT EXISTS quality_gates_object_idx ON quality_gates (object_type, object_id, status)',
      `CREATE TABLE IF NOT EXISTS agent_conversations (
        id TEXT PRIMARY KEY,
        project_id TEXT NOT NULL,
        role TEXT NOT NULL,
        content TEXT NOT NULL,
        metadata_json TEXT NOT NULL DEFAULT '{}',
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL,
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
      )`,
      'CREATE INDEX IF NOT EXISTS agent_conversations_project_idx ON agent_conversations (project_id, created_at)',
    ],
  },
];
