import type { Migration } from './types';

export const phase6Migrations: Migration[] = [
  {
    id: '0007_phase6_asset_versions',
    version: 7,
    statements: [
      `CREATE TABLE IF NOT EXISTS assets (
        id TEXT PRIMARY KEY,
        project_id TEXT NOT NULL,
        legacy_id TEXT NOT NULL DEFAULT '',
        type TEXT NOT NULL,
        name TEXT NOT NULL,
        description TEXT NOT NULL DEFAULT '',
        identity_anchor_json TEXT NOT NULL DEFAULT '[]',
        prompt TEXT NOT NULL DEFAULT '',
        art_style TEXT NOT NULL DEFAULT '',
        canonical_version_id TEXT,
        status TEXT NOT NULL DEFAULT 'active',
        metadata_json TEXT NOT NULL DEFAULT '{}',
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL,
        deleted_at INTEGER,
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
        FOREIGN KEY (canonical_version_id) REFERENCES asset_versions(id) ON DELETE SET NULL
      )`,
      'CREATE UNIQUE INDEX IF NOT EXISTS assets_project_legacy_idx ON assets (project_id, legacy_id)',
      'CREATE INDEX IF NOT EXISTS assets_project_idx ON assets (project_id, type, name, deleted_at)',
      `CREATE TABLE IF NOT EXISTS asset_versions (
        id TEXT PRIMARY KEY,
        project_id TEXT NOT NULL,
        asset_id TEXT NOT NULL,
        artifact_id TEXT,
        version_no INTEGER NOT NULL,
        source TEXT NOT NULL DEFAULT 'manual',
        prompt TEXT NOT NULL DEFAULT '',
        image_path TEXT NOT NULL DEFAULT '',
        image_url TEXT NOT NULL DEFAULT '',
        model_id TEXT NOT NULL DEFAULT '',
        resolution TEXT NOT NULL DEFAULT '',
        status TEXT NOT NULL DEFAULT 'candidate',
        source_script_version_id TEXT,
        usage_record_id TEXT,
        metadata_json TEXT NOT NULL DEFAULT '{}',
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL,
        deleted_at INTEGER,
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
        FOREIGN KEY (asset_id) REFERENCES assets(id) ON DELETE CASCADE,
        FOREIGN KEY (artifact_id) REFERENCES artifacts(id) ON DELETE SET NULL,
        FOREIGN KEY (source_script_version_id) REFERENCES script_versions(id) ON DELETE SET NULL,
        FOREIGN KEY (usage_record_id) REFERENCES usage_records(id) ON DELETE SET NULL
      )`,
      'CREATE UNIQUE INDEX IF NOT EXISTS asset_versions_asset_version_no_idx ON asset_versions (asset_id, version_no)',
      'CREATE INDEX IF NOT EXISTS asset_versions_asset_idx ON asset_versions (asset_id, status, deleted_at)',
      `CREATE TABLE IF NOT EXISTS script_asset_links (
        id TEXT PRIMARY KEY,
        project_id TEXT NOT NULL,
        script_version_id TEXT,
        asset_id TEXT NOT NULL,
        asset_version_id TEXT NOT NULL,
        episode_index INTEGER NOT NULL,
        role TEXT NOT NULL DEFAULT 'reference',
        source TEXT NOT NULL DEFAULT 'manual_script_assets',
        confidence REAL NOT NULL DEFAULT 1,
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL,
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
        FOREIGN KEY (script_version_id) REFERENCES script_versions(id) ON DELETE SET NULL,
        FOREIGN KEY (asset_id) REFERENCES assets(id) ON DELETE CASCADE,
        FOREIGN KEY (asset_version_id) REFERENCES asset_versions(id) ON DELETE CASCADE
      )`,
      'CREATE INDEX IF NOT EXISTS script_asset_links_project_episode_idx ON script_asset_links (project_id, episode_index)',
      'CREATE INDEX IF NOT EXISTS script_asset_links_asset_idx ON script_asset_links (asset_id, asset_version_id)',
      `CREATE TABLE IF NOT EXISTS ip_asset_timeline_entries (
        id TEXT PRIMARY KEY,
        project_id TEXT NOT NULL,
        asset_id TEXT NOT NULL,
        asset_version_id TEXT NOT NULL,
        episode_index INTEGER NOT NULL,
        appearance_type TEXT NOT NULL,
        risk_level TEXT NOT NULL DEFAULT 'low',
        summary TEXT NOT NULL DEFAULT '',
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL,
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
        FOREIGN KEY (asset_id) REFERENCES assets(id) ON DELETE CASCADE,
        FOREIGN KEY (asset_version_id) REFERENCES asset_versions(id) ON DELETE CASCADE
      )`,
      'CREATE INDEX IF NOT EXISTS ip_asset_timeline_project_idx ON ip_asset_timeline_entries (project_id, episode_index, asset_id)',
      "ALTER TABLE script_versions ADD COLUMN asset_summary_json TEXT NOT NULL DEFAULT '{}'",
    ],
  },
];
